// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuccjthxhxfgytevxhtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1Y2NqdGh4aHhmZ3l0ZXZ4aHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzM1MjAsImV4cCI6MjA2MzE0OTUyMH0.u7gJar2a6z79j2nmdWwwPxkHK8cqwTFanrJfqEJvto4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);